spring.application.name=GestorDeDepositos

spring.datasource.url=jdbc:postgresql://localhost:5432/GestorDeDepositos
spring.datasource.username=postgres
spring.datasource.password=Itjhu34l_jei3zqWrRGbb

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never
spring.jpa.show-sql=true

jwt.secret=12345678901234567890123456789012  
jwt.expiration=28800000  

logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.root=INFO

# Configuracion del usuario administrador inicial
app.admin.username=admin
app.admin.password=admin123
app.admin.email=admin@gestordepositos.com
app.admin.firstname=Administrador
app.admin.lastname=Sistema